def say(something):
    import haiku
    haiku = haiku.get_random_haiku()
    print("")
    print("")
    print(" Your Personal Bot")
    print("")
    print("                   ------------------ ")
    print("      o     o      - Hi! My name is - ")
    print("      _\___/_      - Beepbot!       - ")
    print("     |       |     ------------------ ")
    print("     | 0 . 0 |    ")
    print("     |  </>  |    ")
    print("     |_______|      " + something[0])
    print("     ____|____     /   > " + something[1])
    print("  __|         |___/    > " + something[2])
    print(" |  |    S2   |                         ")
    print(" |  |         |       " + haiku[0][0])
    print(" M  |_________|       " + haiku[0][1])
    print("      |    |          " + haiku[0][2])
    print("      O    O         - " + haiku[1])
    print("                     ")
    print(" Beep ... beep ...")
    print("")
