def say(something):
    print("                                 ")
    print("                                 ")
    print("    Your Personal Bot                              ")
    print("                                 ")
    print("            o       o     ------------------------------- ")
    print("             \     /      - Hi! My name is Beepbot!     - ")
    print("            ---------     - I'm your personal bot. - ")
    print("            - 0   0 -     ------------------------------- ")
    print("            -   .   -            ")
    print("            -  </>  -            ")
    print("            ---------      W     " + something[0])
    print("                |         /      " + something[1])
    print("            ---------    /       ")
    print("        -----       ----         ")
    print("        |   -    S2 -            ")
    print("        |   -       -            ")
    print("        M   ---------            ")
    print("              |    |             ")
    print("              O    O             ")
    print("                                 ")
