def say(something):
    import haiku
    haiku = haiku.get_random_haiku()
    print("")
    print("")
    print(" Your Personal Bot")
    print("                                     ")
    print("    o       o     ------------------ ")
    print("     \     /      - Hi! My name is - ")
    print("    ---------     - Beepbot!       - ")
    print("    - 0   0 -     ------------------ ")
    print("    -   .   -    ")
    print("    -  </>  -    ")
    print("    ---------       " + something[0])
    print("         |         /   " + something[1])
    print("     ---------    /    " + something[2])
    print(" -----       ----         ")
    print(" |   -    S2 -            ")
    print(" |   -       -       " + haiku[0][0])
    print(" M   ---------       " + haiku[0][1])
    print("      |    |         " + haiku[0][2])
    print("      O    O         " + haiku[1][0])
    print("                          ")
